[workspace]
channels = ["conda-forge", "bioconda"]
name = "biodataeng"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lab = "jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''"

[dependencies]
python = "3.12.*"
jupyterlab = "*"
r-base = "*"
r-essentials = "*"
r-rlang = "*"
r-tidyverse = "*"
r-dbi = "*"
r-dbplyr = "*"
r-rpostgres = "*"
r-wgcna = "*"
r-seurat = "*"
r-irkernel = "*"
r-biocmanager = "*"
bioconductor-biocgenerics = "*"
bioconductor-biocversion = "*"
bioconductor-biobase = "*"
bioconductor-deseq2 = "*"
bioconductor-edger = "*"
bioconductor-monocle = "*"
bioconductor-clusterprofiler = "*"
"bioconductor-org.hs.eg.db" = "*"
"bioconductor-org.mm.eg.db" = "*"
"bioconductor-org.dr.eg.db" = "*"
"bioconductor-org.rn.eg.db" = "*"
bioconductor-mixomics = "*"
bioconductor-anndatar = "*"

[pypi-dependencies]
black = "*"
ruff = "*"
mypy = "*"
tox = "*"
structlog = "*"
pytest = "*"
pytest-snapshot = "*"
tqdm = "*"
line-profiler = "*"
memory-profiler = "*"
mkdocs = "*"
numpy = "*"
scipy = "*"
statsmodels = "*"
matplotlib = "*"
openpyxl = "*"
python-dotenv = "*"
psycopg = { version = "*", extras = ["binary"] }
sqlalchemy = "*"
sqlalchemy-utils = "*"
pandas = { version = "*", extras = ["performance", "plot", "computation", "excel", "xml", "hdf5"] }
polars = "*"
ibis-framework = { version = "*", extras = ["pandas", "polars", "postgres"] }
requests = "*"
pytrials = "*"
pydantic = "*"
sqlmodel = "*"
alembic = "*"
sqlacodegen = "*"
pandera = { version = "*", extras = ["pandas", "polars", "mypy", "ibis"] }
seaborn = "*"
fastcluster = "*"
pillow = "*"
scikit-learn = "*"
xgboost = "*"
lightgbm = "*"
catboost = "*"
optuna = "*"
hyperopt = "*"
ray = "*"
ipywidgets = "*"
ipympl = "*"
ipytest = "*"
rdkit = "*"
biopython = "*"
bioinfokit = "*"
anndata = "*"
scanpy = { version = "*", extras = ["leiden"] }
torch = "*"
torchvision = "*"
